# -*- coding: utf-8 -*-
"""Saathvika_Bandi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1igamMKXykC26ZTd1QPgAsPPLuKTKFOlP
"""

# Dependencies
!pip install torch torchaudio transformers
!pip install SpeechRecognition
!pip install pyttsx3
!apt-get install espeak
!pip install pydub
!pip install gtts

import speech_recognition as sr
from gtts import gTTS
import pyttsx3
import IPython.display as ipd
from pydub import AudioSegment

AudioSegment.from_mp3("/content/input.mp3").export("/content/input.wav", format="wav")

# Perform speech recognition using Google's Web Speech API and transcribe spoken words from the audio file into text
recognizer = sr.Recognizer()
audio_path = "/content/input.wav"

# Iterating the audio file
with sr.AudioFile(audio_path) as source:
    audio_data = recognizer.record(source)
    # try block
    try:
        # Recognize and transcribe spoken words from the audio file in Hindi (India) using Google's Web Speech API
        # Here the language can be changed by changing language = "hi-IN"
        transcription = recognizer.recognize_google(audio_data, language="hi-IN")
        print("Transcription:", transcription)

        # Initialize the pyttsx3 text-to-speech engine
        engine = pyttsx3.init()

        # Can change the speed of the output by changing rate of the output
        engine.setProperty("rate", 100)

        # Can change the volume of the output by changing the volume from 0 to 1
        engine.setProperty("volume", 1.0)

        # Can change from the pre-defined voice of the pyttsx3 library
        engine.setProperty("voice", "hindi")

        # The output is saved in output.mp3
        engine.save_to_file(transcription, "output.mp3")

    except sr.UnknownValueError:
        # If the speech is not recognised
        print("Speech Recognition could not understand audio")

    except sr.RequestError as e:
        # If the speech could not be translated by the google search API
        print(f"Could not request results from Google Web Speech API; {e}")